baseURL: "https://abhinavkomanduri.github.io"
title: Abhinav Komanduri
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

params:
  description: "Personal academic website of Abhinav Komanduri, PhD student in Electrical & Computer Engineering at the University of Washington."
  position: "PhD Student, Electrical & Computer Engineering"
  school: "University of Washington"
  email: "akomand@uw.edu"
  advisor: "Shwetak Patel"
  advisorURL: "https://homes.cs.washington.edu/~shwetak/"
  lab: "Ubicomp Lab"
  labURL: "https://ubicomplab.cs.washington.edu/"
  cv: "Komanduri_CV.pdf"
  scholar: "https://scholar.google.com/citations?user=dZaIl5EAAAAJ&hl=en&oi=ao"
  github: "https://github.com/abhinavkomanduri"
  linkedin: "https://www.linkedin.com/in/abhinav-komanduri/"

markup:
  goldmark:
    renderer:
      unsafe: true
