baseURL: "https://abhinavkomanduri.github.io" 
title: Abhinav Komanduri
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: about/
          weight: 1 
        - name: Research and Projects
          url: papers/
          weight: 2
        - name: News
          url: news/
          weight: 3
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Abhinav Komanduri's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Abhinav Komanduri
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Abhinav Komanduri
          subtitle: "Hi! I am a rising senior at the University of Arkansas, Fayetteville studying Electrical Engineering. My research interests include embedded systems, hardware security, wearable 
          computing, and human-computing interactions. Applying to PhD programs in the fall! Take a look around to get to know me!"
          imageUrl: "pfp.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: about/
            - name: Research and Projects
              url: papers/
            - name: News
              url: news/

    socialIcons:
        - name: CV
          url: komanduri_abhinav_cv.pdf
        - name: Email
          url: mailto:abhinavk@uark.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=dZaIl5EAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/abhinavkomanduri
        - name: Linkedin
          url: https://www.linkedin.com/in/abhinav-komanduri/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Abhinav Komanduri"
      icon: icon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2